# Generated by Django 4.2.6 on 2023-10-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("last_modified", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CareEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("water", "Watering"),
                            ("fertilize", "Fertilizing"),
                            ("repot", "Repotting"),
                            ("disease", "Disease"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_events",
                        to="plant_care_tracker.plant",
                    ),
                ),
            ],
        ),
    ]
